// Bottom-sheet replacement for the previous full-screen join-pool route.
// Opened from the "+" menu (PoolCreateJoinSheet → "Join with Code") and
// from the EmptyPools state. Uses the @gorhom/bottom-sheet pattern so
// the chrome matches FlexBadgesSheet / PoolsFilterSheet / PoolCreateJoinSheet.

import BottomSheet, {
  BottomSheetBackdrop,
  BottomSheetTextInput,
  BottomSheetView,
  type BottomSheetBackdropProps,
} from '@gorhom/bottom-sheet';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { router } from 'expo-router';
import {
  forwardRef,
  useCallback,
  useImperativeHandle,
  useRef,
  useState,
} from 'react';
import { Linking, Platform, Pressable, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { Icon, Text } from '@/components/ui';
import { joinPool } from '@/lib/api';
import { useHomeData } from '@/lib/HomeDataProvider';
import { fontFamilies, useTheme, withOpacity } from '@/theme';

type Tab = 'code' | 'qr';

// Accept any of these QR payload shapes so a code generated by the web
// app, an iOS Camera deep-link, or even a plain pasted code reach the same
// joinPool path:
//  - https://sportpool.io/join/W58UGD64
//  - https://www.sportpool.io/join/W58UGD64
//  - http://sportpool.io/join/W58UGD64
//  - officepools://join/W58UGD64  (our deep-link scheme)
//  - W58UGD64                     (bare code, in case someone QRs raw text)
const POOL_CODE_RE = /^[A-Z0-9]{6,12}$/;

function extractPoolCode(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const trimmed = raw.trim();
  if (!trimmed) return null;

  // URL-shaped: pull the last /join/<code> segment.
  const joinMatch = trimmed.match(/\/join\/([A-Za-z0-9]+)/i);
  if (joinMatch) {
    const candidate = joinMatch[1].toUpperCase();
    return POOL_CODE_RE.test(candidate) ? candidate : null;
  }

  // Bare code QR — accept anything that looks like a pool code as-is.
  const candidate = trimmed.toUpperCase();
  if (POOL_CODE_RE.test(candidate)) return candidate;
  return null;
}

export type JoinPoolSheetHandle = {
  open: () => void;
  close: () => void;
};

export const JoinPoolSheet = forwardRef<JoinPoolSheetHandle>(function JoinPoolSheet(_, ref) {
  const theme = useTheme();
  const insets = useSafeAreaInsets();
  const sheetRef = useRef<BottomSheet | null>(null);
  const [tab, setTab] = useState<Tab>('code');
  const [poolCode, setPoolCode] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // Tracks whether the BottomSheet itself is on-screen. We mount the
  // CameraView conditionally on this so the camera session is torn down
  // the moment the sheet animates away (panned down, programmatically
  // closed, or after a successful scan-then-navigate).
  const [sheetOpen, setSheetOpen] = useState(false);
  // Used after a successful join so the new pool shows up on the Home
  // and Pools tab cards immediately — same pattern as create-pool.
  const { refresh: refreshHomeData } = useHomeData();
  // Camera permissions for QR scanning. `useCameraPermissions` exposes
  // the current status + a request function. We don't auto-request on
  // mount; we wait until the user actually switches to the QR tab so
  // we don't surface a permission prompt to people who only ever paste
  // a code.
  const [cameraPermission, requestCameraPermission] = useCameraPermissions();
  // Debounce / once-shot guard for barcode callbacks. expo-camera fires
  // `onBarcodeScanned` continuously while a code is in frame; we only
  // want to act on the first valid hit per session.
  const scanLockRef = useRef(false);

  // Reset local state every time the sheet opens so the previous attempt's
  // input / error doesn't leak across opens.
  useImperativeHandle(ref, () => ({
    open: () => {
      setTab('code');
      setPoolCode('');
      setError(null);
      setLoading(false);
      scanLockRef.current = false;
      sheetRef.current?.expand();
    },
    close: () => sheetRef.current?.close(),
  }));

  const renderBackdrop = useCallback(
    (props: BottomSheetBackdropProps) => (
      <BottomSheetBackdrop {...props} appearsOnIndex={0} disappearsOnIndex={-1} opacity={0.4} />
    ),
    [],
  );

  // Shared join flow used by both the manual-code submit and the QR
  // scanner success path. Keeping it in one place means a successful
  // scan exits to the new pool's leaderboard the exact same way a typed
  // code does — no behavioral drift between the two entrypoints.
  async function executeJoin(code: string) {
    setError(null);
    setLoading(true);
    try {
      const joined = await joinPool(code);
      sheetRef.current?.close();
      void refreshHomeData();
      router.navigate(`/pool/${joined.pool_id}`);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to join pool');
      // Reopen the scan lock so the user can re-aim the camera if the
      // first attempt errored (e.g. already a member, pool closed).
      scanLockRef.current = false;
    } finally {
      setLoading(false);
    }
  }

  async function handleSubmit() {
    const trimmed = poolCode.trim().toUpperCase();
    if (!trimmed) return;
    await executeJoin(trimmed);
  }

  function handleBarcodeScanned(result: { data?: string | null }) {
    if (scanLockRef.current || loading) return;
    const code = extractPoolCode(result.data);
    if (!code) {
      // Not a pool QR — show a soft error but keep the scanner live so
      // the user can re-frame on a different code.
      setError("That QR doesn't look like a pool invite.");
      return;
    }
    scanLockRef.current = true;
    setError(null);
    void executeJoin(code);
  }

  const canSubmit = poolCode.trim().length > 0 && !loading;

  return (
    <BottomSheet
      ref={sheetRef}
      index={-1}
      // Dynamic sizing — sheet height tracks BottomSheetView's content
      // height instead of a hardcoded snap point. Avoids the dead-space
      // problem where the static estimate over-allocated whitespace below
      // the Cancel link.
      enableDynamicSizing
      enablePanDownToClose
      backdropComponent={renderBackdrop}
      // Sheet shifts up as the keyboard appears so the input stays visible.
      keyboardBehavior="interactive"
      keyboardBlurBehavior="restore"
      handleIndicatorStyle={{ backgroundColor: theme.colors.silver }}
      backgroundStyle={{ backgroundColor: theme.colors.surface }}
      // Track open/closed state so the QR tab can mount/unmount the
      // CameraView in lockstep with sheet visibility.
      onChange={(idx) => setSheetOpen(idx >= 0)}
    >
      <BottomSheetView
        style={{
          paddingHorizontal: theme.spacing.xl,
          paddingTop: theme.spacing.sm,
          paddingBottom: insets.bottom + theme.spacing.md,
          gap: theme.spacing.lg,
        }}
      >
        {/* Hero icon + title + subtitle — preserves the visual identity
            of the original full-screen join-pool. */}
        <View style={{ alignItems: 'center', gap: theme.spacing.sm }}>
          <View
            style={{
              width: 56,
              height: 56,
              borderRadius: theme.radii.xl,
              backgroundColor: withOpacity(theme.colors.primary, 0.1),
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <Icon name="person.badge.plus" color="primary" size={26} weight="semibold" />
          </View>
          <Text variant="cardTitle" align="center">
            Join a Pool
          </Text>
          <Text variant="body" color="slate" align="center">
            Enter a code or scan a QR to join
          </Text>
        </View>

        <SegmentedTabs tab={tab} onChange={setTab} />

        {tab === 'code' ? (
          <View style={{ gap: theme.spacing.md }}>
            {error ? (
              <View
                style={{
                  padding: theme.spacing.md,
                  borderRadius: theme.radii.md,
                  backgroundColor: theme.colors.redLight,
                }}
              >
                <Text variant="body" color="red" align="center">
                  {error}
                </Text>
              </View>
            ) : null}

            <BottomSheetTextInput
              value={poolCode}
              onChangeText={(value) => {
                setPoolCode(value.toUpperCase());
                setError(null);
              }}
              placeholder="POOL CODE"
              placeholderTextColor={theme.colors.slate}
              autoCapitalize="characters"
              autoCorrect={false}
              maxLength={12}
              style={{
                backgroundColor: theme.colors.mist,
                borderRadius: theme.radii.md,
                paddingHorizontal: theme.spacing.md,
                paddingVertical: theme.spacing.md,
                fontFamily: Platform.OS === 'ios' ? 'Menlo-Bold' : 'RobotoMono_700Bold',
                fontSize: 22,
                letterSpacing: 4,
                textAlign: 'center',
                color: theme.colors.ink,
              }}
            />

            <Pressable
              onPress={handleSubmit}
              disabled={!canSubmit}
              style={({ pressed }) => ({
                flexDirection: 'row',
                alignItems: 'center',
                justifyContent: 'center',
                gap: theme.spacing.sm,
                height: 52,
                borderRadius: theme.radii.md,
                backgroundColor: theme.colors.primary,
                opacity: !canSubmit ? 0.5 : pressed ? 0.85 : 1,
              })}
            >
              {/* Stroked plus-in-circle reads as "add / join" against the
                  primary-blue button. Important: we deliberately omit the
                  `filled` prop here — passing it would tell Lucide to fill
                  every path (circle AND inner plus) with the same white
                  tint, which collapses the plus into the filled disc. */}
              <Icon name="plus.circle.fill" tint="#FFFFFF" size={20} weight="bold" />
              <Text
                style={{
                  fontFamily: fontFamilies.bold,
                  fontSize: 16,
                  color: '#FFFFFF',
                  letterSpacing: 0.2,
                  textAlign: 'center',
                }}
              >
                {loading ? 'Joining…' : 'Join Pool'}
              </Text>
            </Pressable>
          </View>
        ) : (
          <QRScanView
            sheetOpen={sheetOpen}
            permissionGranted={!!cameraPermission?.granted}
            permissionCanAskAgain={cameraPermission?.canAskAgain ?? true}
            permissionChecked={!!cameraPermission}
            onRequestPermission={async () => {
              const next = await requestCameraPermission();
              if (!next.granted && !next.canAskAgain) {
                // User denied permanently. Best we can do is hand them to
                // Settings so they can flip the switch and come back.
                void Linking.openSettings();
              }
            }}
            onBarcodeScanned={handleBarcodeScanned}
            loading={loading}
            error={error}
          />
        )}

        <Pressable
          onPress={() => sheetRef.current?.close()}
          hitSlop={8}
          style={({ pressed }) => ({
            alignSelf: 'center',
            paddingVertical: theme.spacing.sm,
            opacity: pressed ? 0.5 : 1,
          })}
        >
          <Text variant="body" color="slate">
            Cancel
          </Text>
        </Pressable>
      </BottomSheetView>
    </BottomSheet>
  );
});

function SegmentedTabs({ tab, onChange }: { tab: Tab; onChange: (t: Tab) => void }) {
  const theme = useTheme();
  return (
    <View
      style={{
        flexDirection: 'row',
        backgroundColor: theme.colors.mist,
        borderRadius: theme.radii.md,
        padding: theme.spacing.xs,
      }}
    >
      <SegmentButton
        active={tab === 'code'}
        onPress={() => onChange('code')}
        icon="keyboard"
        label="Pool Code"
      />
      <SegmentButton
        active={tab === 'qr'}
        onPress={() => onChange('qr')}
        icon="qrcode"
        label="Scan QR"
      />
    </View>
  );
}

function SegmentButton({
  active,
  onPress,
  icon,
  label,
}: {
  active: boolean;
  onPress: () => void;
  icon: string;
  label: string;
}) {
  const theme = useTheme();
  return (
    <Pressable
      onPress={onPress}
      style={({ pressed }) => ({
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: theme.spacing.xs,
        paddingVertical: theme.spacing.sm,
        borderRadius: theme.radii.sm,
        backgroundColor: active ? theme.colors.surface : 'transparent',
        opacity: pressed ? 0.7 : 1,
      })}
    >
      <Icon name={icon} color={active ? 'primary' : 'slate'} size={14} weight="semibold" />
      <Text
        variant="body"
        color={active ? 'primary' : 'slate'}
        style={{ fontFamily: fontFamilies.bold }}
      >
        {label}
      </Text>
    </Pressable>
  );
}

type QRScanViewProps = {
  sheetOpen: boolean;
  permissionGranted: boolean;
  permissionCanAskAgain: boolean;
  permissionChecked: boolean;
  onRequestPermission: () => void;
  onBarcodeScanned: (result: { data?: string | null }) => void;
  loading: boolean;
  error: string | null;
};

function QRScanView({
  sheetOpen,
  permissionGranted,
  permissionCanAskAgain,
  permissionChecked,
  onRequestPermission,
  onBarcodeScanned,
  loading,
  error,
}: QRScanViewProps) {
  const theme = useTheme();

  // Square viewfinder. Sized so it fits comfortably in the sheet without
  // bleeding past the segmented tabs or the cancel link.
  const FRAME_SIZE = 260;

  // Pre-permission state — first time the user lands here, prompt them
  // to enable the camera. We don't auto-trigger the permission dialog on
  // sheet open because that would surface a system prompt for users who
  // never touch the QR tab.
  if (!permissionChecked || !permissionGranted) {
    const isHardDenied = permissionChecked && !permissionGranted && !permissionCanAskAgain;
    return (
      <View
        style={{
          alignItems: 'center',
          gap: theme.spacing.md,
          paddingVertical: theme.spacing.xl,
          paddingHorizontal: theme.spacing.lg,
        }}
      >
        <Icon name="qrcode.viewfinder" color="slate" size={40} />
        <Text variant="body" color="slate" align="center">
          {isHardDenied
            ? 'Camera access is off for SportPool. Enable it in Settings to scan a pool QR.'
            : 'Allow camera access to scan a pool QR code.'}
        </Text>
        <Pressable
          onPress={onRequestPermission}
          style={({ pressed }) => ({
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: theme.spacing.sm,
            paddingVertical: 12,
            paddingHorizontal: theme.spacing.lg,
            borderRadius: theme.radii.md,
            backgroundColor: theme.colors.primary,
            opacity: pressed ? 0.85 : 1,
          })}
        >
          <Text
            style={{
              fontFamily: fontFamilies.bold,
              fontSize: 15,
              color: '#FFFFFF',
              letterSpacing: 0.2,
            }}
          >
            {isHardDenied ? 'Open Settings' : 'Enable Camera'}
          </Text>
        </Pressable>
      </View>
    );
  }

  return (
    <View style={{ alignItems: 'center', gap: theme.spacing.sm }}>
      {error ? (
        <View
          style={{
            padding: theme.spacing.sm,
            borderRadius: theme.radii.md,
            backgroundColor: theme.colors.redLight,
            alignSelf: 'stretch',
          }}
        >
          <Text variant="body" color="red" align="center">
            {error}
          </Text>
        </View>
      ) : null}

      {/* Camera viewfinder — mounted only while the sheet is on-screen so
          the OS doesn't keep the camera session alive once the user pans
          the sheet away. Square clip + brand-colored frame corners. */}
      <View
        style={{
          width: FRAME_SIZE,
          height: FRAME_SIZE,
          borderRadius: theme.radii.lg,
          overflow: 'hidden',
          backgroundColor: theme.colors.ink,
          position: 'relative',
        }}
      >
        {sheetOpen ? (
          <CameraView
            style={{ flex: 1 }}
            facing="back"
            barcodeScannerSettings={{ barcodeTypes: ['qr'] }}
            // Pause scans while a join is in flight so the same code
            // doesn't fire onBarcodeScanned twice.
            onBarcodeScanned={loading ? undefined : onBarcodeScanned}
          />
        ) : null}

        {/* Decorative L-corners — pure visual affordance for "aim here".
            Not interactive, so they sit on top of the CameraView without
            stealing touches. */}
        <CornerMark style={{ top: 0, left: 0 }} corner="tl" />
        <CornerMark style={{ top: 0, right: 0 }} corner="tr" />
        <CornerMark style={{ bottom: 0, left: 0 }} corner="bl" />
        <CornerMark style={{ bottom: 0, right: 0 }} corner="br" />
      </View>

      <Text variant="body" color="slate" align="center">
        {loading ? 'Joining…' : 'Point the camera at a pool QR'}
      </Text>
    </View>
  );
}

function CornerMark({
  style,
  corner,
}: {
  style: { top?: number; right?: number; bottom?: number; left?: number };
  corner: 'tl' | 'tr' | 'bl' | 'br';
}) {
  const theme = useTheme();
  const LENGTH = 28;
  const THICK = 3;
  const RAD = 6;
  // Each L is two absolutely-positioned bars (one horizontal, one
  // vertical) joined at the corner. Rounding the outer-facing edge only
  // gives a tidy rounded-L look without weird inner curves.
  const isTop = corner === 'tl' || corner === 'tr';
  const isLeft = corner === 'tl' || corner === 'bl';
  return (
    <View style={{ position: 'absolute', ...style, width: LENGTH, height: LENGTH }}>
      {/* Horizontal arm */}
      <View
        style={{
          position: 'absolute',
          [isTop ? 'top' : 'bottom']: 0,
          [isLeft ? 'left' : 'right']: 0,
          width: LENGTH,
          height: THICK,
          backgroundColor: '#FFFFFF',
          borderTopLeftRadius: isTop && isLeft ? RAD : 0,
          borderTopRightRadius: isTop && !isLeft ? RAD : 0,
          borderBottomLeftRadius: !isTop && isLeft ? RAD : 0,
          borderBottomRightRadius: !isTop && !isLeft ? RAD : 0,
        }}
      />
      {/* Vertical arm */}
      <View
        style={{
          position: 'absolute',
          [isTop ? 'top' : 'bottom']: 0,
          [isLeft ? 'left' : 'right']: 0,
          width: THICK,
          height: LENGTH,
          backgroundColor: '#FFFFFF',
          borderTopLeftRadius: isTop && isLeft ? RAD : 0,
          borderTopRightRadius: isTop && !isLeft ? RAD : 0,
          borderBottomLeftRadius: !isTop && isLeft ? RAD : 0,
          borderBottomRightRadius: !isTop && !isLeft ? RAD : 0,
        }}
      />
    </View>
  );
}
